name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: false
          activate-environment: wxenv
          channels: conda-forge
          conda-remove-defaults: true

      - name: Install wxWidgets
        run: |
          conda install -y conda-forge::wxwidgets

      - name: Configure
        env:
          WX_CONFIG: $CONDA/bin/wx-config 
        run: |
          cmake -S . -B build

      - name: Build
        run: |
          cmake --build build
